replacing zone of skin with skin of body
obophenotype/bio-attribute-ontology pull request #134
Opened 2022-09-08 22:11 UTC by megbalk

issue #41

2022-10-13 23:02 UTC, megbalk commented
@rays22 how do I rerun the dosdp pattern file?

2022-10-14 14:12 UTC, rays22 commented
> @rays22 how do I rerun the dosdp pattern file?

I think the `definitions.owl` axioms get regenerated automatically in OBA if you change any of the tsv template data files in a PR.
Otherwise, you can turn the [template tables into OWL axioms](https://oboacademy.github.io/obook/tutorial/dosdp-odk/) by running this:

```
sh run.sh make ../patterns/definitions.owl -B IMP=false
```

2022-10-14 15:08 UTC, rays22 requested changes

2022-10-14 15:08 UTC, rays22 commented on src/patterns/data/default/entity_attribute.tsv
> +OBA:VT1000425	skin mass	UBERON:0002097	skin of body	PATO:0000125	mass
I would keep the original `UBERON:0000014	zone of skin ` entity here.
See my comments here: https://github.com/obophenotype/bio-attribute-ontology/issues/41#issuecomment-1279130088

2022-10-19 23:27 UTC, closed without merging