IMPC Terms
obophenotype/bio-attribute-ontology pull request #177
Opened 2022-12-13 11:14 UTC by souzadevinicius

This PR solves this [issue](https://github.com/obophenotype/bio-attribute-ontology/issues/176) partially.

2022-12-13 13:43 UTC, matentzn requested changes
Great job.

There are a number of irrelevant changes in this PR that belong in your VT alignment PR, like src/mappings/oba-vt.sssom.tsv

You should be careful when you create branches to _always create them off `main/master` branch_. You seem to be creating them of feature branches.

2022-12-13 13:44 UTC, souzadevinicius commented on src/ontology/oba.Makefile
> +#########################################
> I think you need to be more careful with your branches - these changes seem to belong to another branch!

Sorry

2022-12-15 12:26 UTC, matentzn commented on src/ontology/oba.Makefile
> +#########################################
Can you make a new PR, copying only the files you intended to change?

2022-12-15 12:48 UTC, matentzn commented
I reverted the files.

2022-12-15 12:50 UTC, matentzn commented on src/ontology/oba.Makefile
> +#########################################
Done.

2022-12-15 12:53 UTC, matentzn requested changes
Please

- [x] Merge all tables in the PR into a single table (called impc.tsv) with an additional column "pattern name"
- [x] The additional column "pattern name" should have the name of the tsv files the row came from
- [x] The merge should be using use `defined_class` as primary key, but there are many other partially overlapping columns. Normal pandas merge?

2022-12-20 18:06 UTC, matentzn commented
Do we still need this PR? Probably not right? We only care now about @ar-ibrahim curation of the IMPC terms!

2022-12-20 19:55 UTC, souzadevinicius commented
> Do we still need this PR? Probably not right? We only care now about @ar-ibrahim curation of the IMPC terms!

No, we didn't

2023-03-20 17:19 UTC, closed without merging