Update SSSOM mapping files
obophenotype/bio-attribute-ontology pull request #208
Opened 2023-02-03 11:09 UTC by rays22

Following [SOP here.](https://obophenotype.github.io/bio-attribute-ontology/editors-guide/)

2023-02-03 12:38 UTC, matentzn commented
Why is the diff so large?

2023-02-03 16:09 UTC, rays22 commented
> Why is the diff so large?

I have updated some term labels and fixed an incorrect mapping.

2023-02-03 16:38 UTC, rays22 commented
> Why is the diff so large?

It looks like that somebody has also updated the match_type on every line of the vt sssom table.

2023-02-05 07:53 UTC, matentzn commented on src/mappings/oba-efo-mapping-exclusions.sssom.tsv
> +EFO:0005514	HER2 status	skos:exactMatch	sssom:NoMapping	HumanCurated	tumor level measurements out of scope for OBA
It is important that this is excellent suggestion is communicated in your meetings with GWAS.

2023-02-05 07:55 UTC, matentzn requested changes
Please reduce the diff, the mapping_justification should be always `semapv:ManualMappingCuration` and I am worried that I made some changes to these files without updating them on Google Docs (during the paper writing)

2023-07-06 13:55 UTC, rays22 commented
> Please reduce the diff, the mapping_justification should be always `semapv:ManualMappingCuration` and I am worried that I made some changes to these files without updating them on Google Docs (during the paper writing)

I have reduced the size of the diff by using `semapv:ManualMappingCuration` for mapping_justification.

2023-07-07 11:49 UTC, matentzn approved these changes
Looks great!

2023-07-07 12:33 UTC, merged