Added new OBA protein terms + refreshed imports
obophenotype/bio-attribute-ontology pull request #264
Opened 2023-06-29 15:34 UTC by ar-ibrahim

- issue #250

2023-07-01 09:57 UTC, rays22 requested changes
You need to remove the duplicate/triplicate OBA classes to fix the QC errors.

2023-07-01 09:57 UTC, rays22 commented on src/patterns/data/default/entity_attribute_location.tsv
Equivalents of the new classes below are being defined multiple times in your `entity_attribute_location.tsv` table in the PR. You need to remove them from to fix the QC errors:

```
OBA:2050317
OBA:2050331
OBA:2050313
OBA:2050265
OBA:2050329
OBA:2050328
```

2023-07-03 09:09 UTC, ar-ibrahim commented on src/patterns/data/default/entity_attribute_location.tsv
Hi Ray! Yeh was an easy to understand QC message for a change :). Will fix.

2023-07-04 12:57 UTC, ar-ibrahim commented
@rays22 Fixed all the duplications but not sure what the new errors are.

2023-07-05 10:56 UTC, rays22 approved these changes
These trait terms look fine. I guess some of the EFO terms these trait terms are meant to match may refer to more specific anatomical location (like serum), but you could not tell without finding and re-visiting the original dataset and publication which prompted the creation of the EFO term.

2023-07-06 08:14 UTC, ar-ibrahim commented
Considering that all these terms are protein terms, it is most likely they were measured in blood/serum. But like you said, we can't make that assumption without going back to the original datasets.

2023-07-06 08:15 UTC, merged